# Generated by Django 5.1.4 on 2026-07-06 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('pub', 'Pub'), ('restaurant', 'Restaurant'), ('function_space', 'Function space')], default='pub', max_length=20)),
                ('location', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=64)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('type', models.CharField(choices=[('sale', 'Sale'), ('void', 'Void'), ('refund', 'Refund')], db_index=True, max_length=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('staff_id', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='ops.venue')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TransactionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=200)),
                ('qty', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ops.transaction')),
            ],
            options={
                'indexes': [models.Index(fields=['item_id'], name='ops_transac_item_id_7f263a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['venue', 'timestamp'], name='ops_transac_venue_i_1b7fe5_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['timestamp', 'type'], name='ops_transac_timesta_3c3e89_idx'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(fields=('venue', 'external_id'), name='unique_venue_transaction'),
        ),
    ]
